web3swift/ABIv2/Classes/ABIv2TypeParser.swift, web3swift/HookedFunctions/Classes/Web3+Wallet.swift, web3swift/ObjectiveCbridge/Classes/Web3+Eth+ObjC.swift, web3swift/Promises/Classes/Promise+Batching.swift, web3swift/Promises/Classes/Promise+HttpProvider.swift, web3swift/Promises/Classes/Promise+Web3+Eth+Call.swift, web3swift/Promises/Classes/Promise+Web3+Eth+EstimateGas.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetAccounts.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetBalance.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetBlockByHash.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetBlockByNumber.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetBlockNumber.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetGasPrice.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetTransactionCount.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetTransactionDetails.swift, web3swift/Promises/Classes/Promise+Web3+Eth+GetTransactionReceipt.swift, web3swift/Promises/Classes/Promise+Web3+Eth+SendRawTransaction.swift, web3swift/Promises/Classes/Promise+Web3+Eth+SendTransaction.swift, web3swift/Promises/Classes/Promise+Web3+Personal+Sign.swift, web3swift/Promises/Classes/Promise+Web3+Personal+UnlockAccount.swift, web3swift/Web3/Classes/Web3+Eth.swift, web3swift/Web3/Classes/Web3+EventParser.swift, web3swift/Web3/Classes/Web3+TransactionIntermediate.swift, web3swift/Web3/Classes/Web3.swift
Hi Alex,
from issue: https://github.com/BANKEX/web3swift/issues/194
I've added a String description to the Web3Error enum in Web3.swift.  Then modified whenever an error was created that required the description.
=> adding description string to Web3Error

web3swift.xcodeproj/project.pbxproj, web3swift/Promises/Classes/Promise+Web3+TxPool.swift, web3swift/Web3/Classes/Web3+Instance.swift, web3swift/Web3/Classes/Web3+JSONRPC.swift, web3swift/Web3/Classes/Web3+Methods.swift, web3swift/Web3/Classes/Web3+TxPool.swift, web3swiftTests/web3swift_local_node_Tests.swift
This is my work for this issue. [#36](https://github.com/matterinc/web3swift/issues/36) 
Infura doesn't provide txpool api, so I just tested at local environment synced with rinkeby network.
=> adds txpool function and its local node test

Sources/web3swift/Utils/ENS/ENSResolver.swift, Sources/web3swift/Web3/Web3+Utils.swift
Updated the Resolver ABI and added the `interfaceImplementer` function. 
Use this function to get the address of the `ETHRegistrarController` like so:
```swift
public enum InterfaceID: String {
case legacyRegistrar = "0x7ba18ba1"
case permanentRegistrar = "0x018fac06"
case baseRegistrar = "0x6ccb2df4"
}
// Get the ETHRegistrarController's address
let controller = try! ens.resolver?.interfaceImplementer(forNode: "eth", interfaceID: InterfaceID.permanentRegistrar.rawValue)
``` 
New resolver code: https://ropsten.etherscan.io/address/0x44385b20865fe3578e56aa0e9f7ec534deb10501#code
Docs on this are at: https://docs.ens.domains/contract-api-reference/.eth-permanent-registrar#discovery
=> Update ENS Resolver

Documentation/Usage.md, README.md, Sources/web3swift/Convenience/Decodable+Extensions.swift, Sources/web3swift/Convenience/Encodable+Extensions.swift, Sources/web3swift/Web3/Web3+Eth+Websocket.swift, Sources/web3swift/Web3/Web3+InfuraProviders.swift, Sources/web3swift/Web3/Web3+WebsocketProvider.swift, Tests/web3swiftTests/web3swift_Websockets_Tests.swift, web3swift.xcodeproj/project.pbxproj
This fixes #188 
- More convenience methods
- Fixed some errors
- No need to write delay between connection and subscribing
=> Websockets improvements and fixes

Sources/web3swift/KeystoreManager/BIP39.swift
Exposing the list of words will make it easier for an application to implement advanced mnemonic phrase validation and word completion.
=> Expose BIP39 words and separator

Sources/web3swift/EthereumABI/ABIElements.swift
*[Reposted because the repository was recreated]*
Dear all:
If a require statement with a message aborts the reading function, an unexpected value may be returned as a response.
For example, if you call the following function,
```solidity
function testC3( uint val ) public pure returns( uint256 ){
require( val != 0, "aborted by testC3" );
return( 0 );
}
```
The following response will be returned.
> // Succeeded: testC3( 1 )
> ["0": 0]
> 
> // aborted: testC3( 0 )
> ["0": 3963877391197344453575983046348115674221700746820753546331534351508065746944]
If the reading function is aborted by a require statement that has a message, it seems that the data with the following configuration will be returned.(By the way, if there is no message specified in the require statement, [0] bytes will be …
=> [recreated] Detect read function aborting by messaged require statement

Sources/web3swift/EthereumABI/ABIParsing.swift
Fix crash when parsing custom ABI Contract
fix #333
=> fix crash when 'payable' nil

.gitmodules, Package.swift, Sources/libscrypt/include/libscrypt.h, Sources/libscrypt/include/module.modulemap, Sources/web3swift/Convenience/CryptoExtensions.swift, Sources/web3swift/KeystoreManager/BIP32Keystore.swift, Sources/web3swift/KeystoreManager/BIP39.swift, Sources/web3swift/KeystoreManager/EthereumKeystoreV3.swift, Sources/web3swift/Utils/Calculations/PBKDF2+Calculate.swift, Sources/web3swift/Utils/Calculations/Scrypt+Calculate.swift, web3swift.podspec, web3swift.xcodeproj/project.pbxproj
Update performance of import account via private key / secret phrase from 6 sec to 0 sec.
=> Update perfomance of import account

Sources/web3swift/Web3/Web3+Structures.swift
TransactionDetails was incorrectly returning blockNumber as transactionIndex. Corrected the property key to return the correct value.
fixes #464
[re-submit as the previous one got corrupted]
=> Fix for transactionIndex incorrectly returning blockNumber

Sources/web3swift/EthereumABI/ABIDecoding.swift
This PR fixes #429 . When decoding a tuple that is not static or an array with a subtype that is not static, the second value in the tuple returned by [`decodeSignleType`](https://github.com/skywinder/web3swift/blob/5b45521c05006195ccd5109d24570e35150c87e1/Sources/web3swift/EthereumABI/ABIDecoding.swift#L35) is a pointer to the next element, NOT the length of the consumed element. So when decoding such an element within a tuple, [`consumed`](https://github.com/skywinder/web3swift/blob/5b45521c05006195ccd5109d24570e35150c87e1/Sources/web3swift/EthereumABI/ABIDecoding.swift#L176) should be set to consumedUnwrapped, NOT incremented by consumedUnwrapped.
=> Fix decoding dynamic tuples and arrays with dynamic subtypes within tuples

Tests/web3swiftTests/localTests/web3swiftKeystoresTests.swift, Tests/web3swiftTests/remoteTests/web3swiftENSTests.swift
Fix the deprecated warnings for Variant.sha512, replaced with Variant.sha2(.sha512)
=> Fix warnings in tests for .sha512

Sources/web3swift/Tokens/ERC721/Web3+ERC721.swift, Sources/web3swift/Tokens/ERC721x/Web3+ERC721x.swift
Change method name used in `tokenURI(tokenId:)` from *"tokenId"* to *"tokenURI"* for both `ERC721` and `ERC721x` tokens.
Fixes #419
=> Fix tokenURI method name for ERC721 and ERC721x tokens

Sources/web3swift/Transaction/EthereumTransaction.swift, Sources/web3swift/Web3/Web3+Structures.swift
Provides some basic tolerance if a EIP-1559 [or future] unknown envelope is encountered. Decoding is abandoned if the field type is present and not 0. Otherwise if 0 or not present decoding is allowed as it is a legacy encoding.
Also included are some range checks at specific places to prevent the overflow condition from happening that results in the precondition trigger in the BigUInt library from halting execution. The result of the subsequent calculation will be incorrect, but the data going in was incorrect anyway... at least it doesn't crash.
fixes #463
=> Provide basic tolerance to EIP-1559 data

Sources/web3swift/HookedFunctions/Web3+BrowserFunctions.swift, Sources/web3swift/Transaction/EthereumTransaction.swift, Sources/web3swift/Web3/Web3+Options.swift, Sources/web3swift/Web3/Web3+Structures.swift
Changed the parsing in TransactionInBlock to properly use the Decodable protocol instead of unnecessarily switching over to JSON parsing
Removed all the old (now completely dead) JSON based parsing code. No point in keeping the JSON code as it duplicates the Decodable code, and makes code maintenance more difficult
=> Remove dead JSON code

Sources/web3swift/EthereumABI/ABIDecoding.swift, Sources/web3swift/Transaction/TransactionSigner.swift, Sources/web3swift/Web3/Web3+Structures.swift
I've consolidated a number of smaller issues into one here, for ease
1) Re-instates PR #440
2) Patches 440 so that it doesn't break by replacing the `fallthrough` with the expected result 
-- closes #429
3) Fixes function name typo identified in 440 (all calling instances fixed as well)
4) fixes TransactionOptions using the wrong key to decode callOnBlock (was using nonce)
-- this exposed a bug in the TransactionOptions decoding
5) fixes decode logic in TransactionOptions to properly work if a given key is not present
-- as it was it would throw an invalid value error, instead of falling to the provided default in the `if let`
-- consequently this probably fixes #469
6) fixes an unsafe forced unwrap in the signing routines in EthereumTransaction
=> mini-rollup of several issues

.swiftlint.yml
As the title says, simply enables the indentation rule to swiftlint
=> add indentation check [default is 4 spaces per tab-stop]

Sources/web3swift/Web3/Web3+Structures.swift
Quick PR to restore some things that got reverted along the way.
1) Restore the fix in #484 (originally #465) that fixed `transactionIndex` incorrectly being decoded using the `blockNumber` key
2) Restore the lint cleanup (#495) in Web3+Structures that was undone along the way
=> Bug fix/transaction index

Documentation/README.md, Documentation/Usage.md, README.md
Updated the documentation to mention EIP-1559 (and the other new EIP's supported). As well as added some basic documentation on how to create transactions utilizing them.
=> Update documentation for EIP-1559 support

Sources/web3swift/Utils/EIP/EIP712.swift
Added an manual memberwise initializer for the `SafeTx` struct, as the auto-generated default initializer will only ever be `internal` access, thus inaccessible to any apps.
Elevated the EIP712 class and members to public, as they are otherwise 'internal' and inaccessible
Fixes #554
=> Fix access level for EIP-712 related objects

Sources/web3swift/Transaction/EthereumTransaction.swift, Sources/web3swift/Web3/Web3+Options.swift
Restored the `fromJSON` functions that were removed back in `2.5.1` by one of my PR's as they were no longer referenced internally. 
As they are part of the public API they should have been refactored and marked as `deprecated`, instead of removed. I've corrected that here.
=> Restore public API `fromJSON()` functions

Sources/web3swift/Web3/Web3+Options.swift
This is a PR to fix the bug spotted in #569 where `TransactionOptions` was incorrectly using the `to` key instead of `from` when decoding for `from`
=> correct the decoding key for `from` in `transactionOptions`

Sources/web3swift/Contract/ContractProtocol.swift, Sources/web3swift/KeystoreManager/IBAN.swift, Sources/web3swift/Tokens/ERC1376/Web3+ERC1376.swift, Sources/web3swift/Transaction/EthereumParameters.swift, Sources/web3swift/Web3/Web3+Options.swift
Added initializers to **public** structs that had none.
By default, structs have initializers that are usable within the project because these initializers have an `internal` access modifier. 
That initializer is obviously inaccessible when some library is used as a dependency in a different project.
Example of initializers available in 3rd party project for `EthereumParameters` (default internal initializer is not visible):
=> Chore: public structs with initializers

Sources/web3swift/Utils/EIP/EIP681.swift, Tests/web3swiftTests/localTests/EIP681Tests.swift
_Authors:  @JeneaVranceanu, @a-tkchnk_
-----------------------
Having EIP681 link like this one:
```
ethereum:0x9aBbDB06A61cC686BD635484439549D45c2449cc@2828/functionName123?string[]=[123,2,5000,wwweer2-=!]
```
during parsing will result in loss of query parameters and function name and the result would be the following link:
```
ethereum:0x9aBbDB06A61cC686BD635484439549D45c2449cc@2828
```
1) EIP681 parsing of arrays in query parameters. Tuples are not yet handled.
2) Encoding of `EIP681Code.parameters` parameters usable in URL.
3) Added `func makeEIP681Link(urlEncoded: Bool) -> String?` to create EIP681 link from `EIP681Code`. `EIP681Code` structure is used to create an EIP681 URL in a `String` representation with an option to URL encode the EIP681 link before it's returned so it's an …
=> Fix for EIP681: parsing of arrays and encoding of EIP681Code into URL

Sources/web3swift/Utils/EIP/EIP712.swift, Sources/web3swift/Web3/Web3+Signing.swift, Tests/web3swiftTests/localTests/EIP712Tests.swift
Fix for https://github.com/skywinder/web3swift/issues/617
--------
Function `eip712encode` was built to allow to encode any model that implements `EIP712Hashable` but due to the way it's declared in a project it's not possible to use is. 
The only function aimed at producing EIP-712 compliant signature was `Web3Signer.signEIP712`. This function was correctly with one major flaw - the only message it's able to sign is `struct SafeTx` - the Gnosis Safe Transaction model.
Modifying the message type from `SafeTx` to `EIP712Hashable` was enough to fix the issue.
I decided to go a bit further and clean up `EIP712.swift`.
`SafeTx` was renamed to `GnosisSafeTx`, docs were added to give it more clarity.
Note that renaming `struct SafeTx` led to EIP712 tests failing as class/struct names are used …
=> fix: EIP712 - allow arbitrary EIP712Hashable data models

Sources/web3swift/Operations/ReadTransaction.swift
`ReadOperation` class has internal `CodableTransaction`.
`data` property is saved into that `CodableTransaction` thus it must be returned from it as well.
Additionally, no other code in the `ReadOperation` was setting the value for `data`.
=> fix: ReadOperation data wasn't set and was returned incorrectly

Sources/web3swift/Tokens/ERC20/Web3+ERC20.swift, Sources/web3swift/Tokens/ST20/Web3+ST20.swift, Tests/web3swiftTests/localTests/ERC20ClassTests.swift, Tests/web3swiftTests/localTests/ERC20Tests.swift, Tests/web3swiftTests/remoteTests/ST20AndSecurityTokenTests.swift
This looks like a bug in async/await API. If a similar bug report for Swift isn't found it will be reported.
=> fix: ERC20 read properties function fixed - multiple inlined async/await was causing issues

Sources/web3swift/Utils/EIP/EIP4361.swift, Tests/web3swiftTests/localTests/EIP4361Test.swift
Enhanced EIP4361 feature: `EIP4361.validate(...)` returns validation object that holds:
- `isEIP4361` flag that tells if the message given for validation represents EIP4361;
- `isValid` - tells if EIP4361 message is meeting all requirements;
- optional `EIP4361` that is safe to force unwrap if `isValid` equals `true`;
- a dictionary of all successfully extracted (not parsed) fields with raw values for each field. Values are accessed by a new enum `EIP4361Field`.
This combination allows getting the reason for failed message parsing, e.g. if `capturedFields` does not contain value for `EIP4361Field.address` it's safe to assume that message does not contain the address field which is required.
=> fix: detailed response of parsing EIP4361

Sources/Core/EthereumABI/ABIDecoding.swift, Sources/Core/EthereumABI/ABIElements.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+Call.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+EstimateGas.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+FeeHistory.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetAccounts.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetBalance.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetBlockByHash.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetBlockByNumber.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetBlockNumber.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetCode.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetGasPrice.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetTransactionCount.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetTransactionDetails.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+GetTransactionReceipt.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+SendRawTransaction.swift, Sources/web3swift/EthereumAPICalls/Ethereum/Eth+SendTransaction.swift, Sources/web3swift/Web3/Web3+Contract.swift, Tests/web3swiftTests/localTests/AdvancedABIv2Tests.swift, Tests/web3swiftTests/localTests/BasicLocalNodeTests.swift, Tests/web3swiftTests/localTests/PersonalSignatureTests.swift, Tests/web3swiftTests/localTests/TestHelpers.swift, Tests/web3swiftTests/localTests/UserCases.swift, Tests/web3swiftTests/remoteTests/InfuraTests.swift
- Removed some debugging commented code. You'll never know if you need it again and when, so it's best to use it while developing but not commit it into the repository;
- Reduced the number of lines required for some web3+eth calls;
- Cleaned up a few tests.
=> chore: some clean up of web3 eth calls, comments and tests

Sources/web3swift/Utils/EIP/EIP4361.swift, Tests/web3swiftTests/localTests/EIP4361Test.swift
This PR includes regular expression fixes for extraction of all fields that could be present in EIP4361.
Regular expressions are duplicated and modified to support the extraction of any characters present for each individual field.
That allows us to get the idea of what is wrong with the EIP4361, what fields have and don't have any values set and which values are invalid.
=> fix: EIP4361 - improved validation by adding ability to extract invalid values for all fields

Sources/Core/EthereumNetwork/Request/APIRequest+Methods.swift
If there is an error during the execution of a JSON RPC request we may receive a response containing the error information.
See JSON Error object specification: https://www.jsonrpc.org/specification#error_object
Here is an example of an error before:
And here is the same error after error object parsing was added:
=> feat: added support for JSON RPC Error object

Sources/Core/EthereumNetwork/Request/APIRequest+Methods.swift
Fixes range of server error check - as otherwise this condition will throw `Fatal error: Range requires lowerBound <= upperBound`.
=> Fix range of JsonRpcErrorCode

Tests/web3swiftTests/remoteTests/EIP1559Tests.swift
Adds tests for EIP1559 transactions on Mainnet and Goerli - to verify that transaction configurations work when sending ether.
[Discussed on Discord](https://discord.com/channels/852230666292559882/855075850771496971/1034863420018798653).
=> Add tests for EIP1559 transactions on Mainnet and Goerli

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation-request.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Added Issue templates for:
- Bug report
- Documentation
- Feature request
Closes #643
=> feat: Add Issues template forms

.github/ISSUE_TEMPLATE/bug_report.yml
- Fixed YAML syntax error caused in bug_report template.
=> fix: Fix syntax error in bug_report template

README.md
Adds a development section to explain how to run the local blockchain (ganache) for testing.
Not sure if that's also what you meant with https://github.com/web3swift-team/web3swift/issues/431 @yaroslavyaroslav
=> Update README. Add development section

Sources/Core/Contract/ContractProtocol.swift
Motivation: given ABI with multiple methods with same name and different input count [[example](https://github.com/JoinColony/colonyJS/blob/main/src/abis/flwss/IColonyNetwork.json#L1151-L1158)], add ability to select correct method. 
Implementation: instead of just `first` method - select by number of input parameters.
=> Add support for multiple contract methods with same name

Sources/Core/Web3Error/Web3Error.swift, Tests/web3swiftTests/localTests/Web3ErrorTests.swift
PR contains breaking change! Changed type of `errorDescription: String` to `errorDescription: String?`.
This change is easy to "fix" but still it's breaking.
Improved output of the error when calling `error.localizedDescription` and the error is of type `Web3Error`.
Before (useless output):
```
2022-11-11 17:56:25.037294+0200 xctest[49120:505590] The operation couldn’t be completed. (Core.Web3Error error 3.)
```
After (copied log from a test case):
```
2022-11-11 17:56:58.722827+0200 xctest[49218:507026] This is a custom description for the test case! web3swift 🥇
```
=> fix!: web3 error output fix

Package.swift
The [Swift Package Index](https://swiftpackageindex.com) package list validation runs on Linux, which [prevents this package from being added](https://github.com/SwiftPackageIndex/PackageList/actions/runs/3454712507/jobs/5766224040) due to:
```
ERROR: package dump failed: error: '852dd406-2b6d-4101-aba4-608728cac732': Invalid manifest
/tmp/852DD406-2B6D-4101-ABA4-608728CAC732/Package.swift:35:22: error: cannot find 'excludeFiles' in scope
exclude: excludeFiles,
^~~~~~~~~~~~
error: invalid manifests at [<AbsolutePath:"/tmp/852DD406-2B6D-4101-ABA4-608728CAC732">]
```
=> Fix validation in SPI package list

Sources/Core/Utility/Utilities.swift, Sources/web3swift/Utils/ENS/ETHRegistrarController.swift, Tests/web3swiftTests/localTests/BasicLocalNodeTests.swift, Tests/web3swiftTests/localTests/LocalTestCase.swift, Tests/web3swiftTests/localTests/NumberFormattingUtilTests.swift, Tests/web3swiftTests/localTests/TransactionsTests.swift, Tests/web3swiftTests/localTests/UtilitiesTests.swift, Tests/web3swiftTests/remoteTests/EIP1559Tests.swift, Tests/web3swiftTests/remoteTests/InfuraTests.swift, Tests/web3swiftTests/remoteTests/PolicyResolverTests.swift
I have read the [issue](https://github.com/web3swift-team/web3swift/issues/667) and it seems that the function in Utilities line 149 was commented but the code inside it was not copied to the function that now causes the recursion
Solution: I only forwarded the call from `formatToEthereumUnits` to `formatToPrecision`, which was the same as before introducing the recursion.
Could you take a look? I ran the unit tests but they crashed as it seems that I need a node running locally and I didn't read the doc yet. If you forward me to the doc I will install the env and I will ran the tests properly before submit the PR
=> Infinite recursion warning #667

.github/pull_request_template.md
Just a suggestion (we can close this PR if you won't approve it).
IMHO, it looks better without extra space in the description.
Before:
After:
&nbsp;
=> chore: remove &nbsp; from PR template

Sources/web3swift/Tokens/ST20/Web3+SecurityToken.swift
SecurityToken ABI located at `Web3.Utils.st20ABI` expects that `investors` function will be called with an argument of type `uint256`. Our implementation of encoding `investors` function call crashed as we gave it no arguments.
More info: `function investors(uint256 _index) external view returns (address)` ([link to the function](https://github.com/PolymathNetwork/polymath-core/blob/2b50c164d39ef27546a15a712d418e0d2f7861be/contracts/interfaces/ISecurityToken.sol#L117) in old version of the contract) was deprecated and is no longer a part of [ISecurityToken.sol](https://github.com/PolymathNetwork/polymath-core/blob/master/contracts/interfaces/ISecurityToken.sol). Instead there are `getInvestors()` and `getInvestorsAt(uint256 _checkpointId)` …
=> fix: deprecated SecurityToken investors function actually expects a uint256 - an index argument

Sources/web3swift/Tokens/ST20/Web3+SecurityToken.swift, Sources/web3swift/Web3/Web3+Contract.swift
Only available for review after #704 is merged as they share 1 commit.
Just cleaning some code. Spacing, indents, redundant lines of code like `let contract = self.contract`.
What has been done:
- removed `parameters: [AnyObject](), extraData: Data()` from all `createReadOperation` calls as these are default values;
- added spacing between `{}` and the code inside;
- removed redundant `self.` uses;
- removed `let contract = self.contract` lines;
- and instead of 
```
let tx = contract.createWriteOperation("setAllowance", parameters: [to, value] as [AnyObject] )!
return tx
```
just returning a result of `contract.create...`.
&nbsp;
&nbsp;
- I have performed a …
=> chore: tokens code clean up

README.md
=> chore: updated /skywinder to /web3swift-team

Sources/web3swift/Web3/Web3+HttpProvider.swift
Adds the ability to initialise `Web3HttpProvider` sync and non optionally.
Motivation: no need to make init sync and optional if client is sure the network provider is working. 
=> Add convenience init for Web3HttpProvider

Tests/web3swiftTests/remoteTests/ENSTests.swift
Added assertions to ENSTests, related to #716 
`testDomainNormalization` lacks the assertion, easy to fix.
`testTTL`  lacks also the assertion, I were checking [EIP137](https://eips.ethereum.org/EIPS/eip-137) and doing some checks with other lib(web3js) and the TTL was zero for "somename.eth". The point here to add this assertion is:
1. ttl will be 0 or greater
2. if something fails it will trigger an exception
The only way to verify a non zero TTL is to change the cache time(TTL) via setter and then run the getter, but being in the mainnet it will generate costs in terms of eth. What do you think?
- I have updated my …
=> ENSTests added assertions

Sources/web3swift/Utils/ENS/ENS.swift
change properties visibility to avoid mutations without using the setters
Related to #721. 
Test passed successfully
=> ENS properties mutability

Sources/web3swift/Tokens/ERC1155/Web3+ERC1155.swift, Sources/web3swift/Tokens/ERC1376/Web3+ERC1376.swift, Sources/web3swift/Tokens/ERC1400/Web3+ERC1400.swift, Sources/web3swift/Tokens/ERC1410/Web3+ERC1410.swift, Sources/web3swift/Tokens/ERC1594/Web3+ERC1594.swift, Sources/web3swift/Tokens/ERC1633/Web3+ERC1633.swift, Sources/web3swift/Tokens/ERC1643/Web3+ERC1643.swift, Sources/web3swift/Tokens/ERC1644/Web3+ERC1644.swift, Sources/web3swift/Tokens/ERC20/Web3+ERC20.swift, Sources/web3swift/Tokens/ERC721/Web3+ERC721.swift, Sources/web3swift/Tokens/ERC721x/Web3+ERC721x.swift, Sources/web3swift/Tokens/ERC777/Web3+ERC777.swift, Sources/web3swift/Tokens/ERC888/Web3+ERC888.swift, Sources/web3swift/Tokens/ST20/Web3+ST20.swift, Sources/web3swift/Tokens/ST20/Web3+SecurityToken.swift, Sources/web3swift/Utils/ENS/ENSBaseRegistrar.swift, Sources/web3swift/Utils/ENS/ENSRegistry.swift, Sources/web3swift/Utils/ENS/ENSReverseRegistrar.swift, Sources/web3swift/Utils/ENS/ETHRegistrarController.swift, Tests/web3swiftTests/localTests/AdvancedABIv2Tests.swift, Tests/web3swiftTests/localTests/PersonalSignatureTests.swift
Fixes #712
* Fixes all remaining ERC's mentioned in #712 
* Some additional (linting) clean ups and fixes for warnings
=> Fix remaining no tx assigns

Sources/web3swift/Tokens/ERC20/Web3+ERC20.swift
This one fixing the ERC20 implementation bug, where `ERC20.transaction` never assigns to `Contract.transaction` for any given method that writes on chain.
Obviously it's a bug spreading all over the `Token` implementation. So this fix should be applied to all `ERC*.swift` methods that returns `WriteOperation`.
This is the special case of #712.
Closes #711
=> `ERC20.transaction` doesn't assigns to `WriteOperation.transaction` property fix

Sources/Web3Core/Structure/Transaction/TransactionReceipt.swift, Tests/web3swiftTests/localTests/TransactionReceiptTests.swift, Tests/web3swiftTests/localTests/TransactionsTests.swift
Based on the comments from Discord. `TransactionReceipt` was missing a field `effectiveGasPrice`.
Tested with ganache v7.7.3 (@ganache/cli: 0.8.2, @ganache/core: 0.8.2).
=> feat: introduced effectiveGasPrice

Example/myWeb3Wallet/Podfile, Example/myWeb3Wallet/myWeb3Wallet.xcodeproj/project.pbxproj
Fixes Example project pod install command warnings
Fetch the branch code
Make a `pod install` without warnings
Open `Example/myWeb3Wallet/myWeb3Wallet.xcworkspace` and make a build without warnings from the Pod project
=> Example project remove pod install warnings

README.md, Sources/web3swift/Operations/ReadOperation.swift, Sources/web3swift/Tokens/ERC1155/Web3+ERC1155.swift, Sources/web3swift/Tokens/ERC1376/Web3+ERC1376.swift, Sources/web3swift/Tokens/ERC1400/Web3+ERC1400.swift, Sources/web3swift/Tokens/ERC1410/Web3+ERC1410.swift, Sources/web3swift/Tokens/ERC1594/Web3+ERC1594.swift, Sources/web3swift/Tokens/ERC1633/Web3+ERC1633.swift, Sources/web3swift/Tokens/ERC1643/Web3+ERC1643.swift, Sources/web3swift/Tokens/ERC1644/Web3+ERC1644.swift, Sources/web3swift/Tokens/ERC20/ERC20BasePropertiesProvider.swift, Sources/web3swift/Tokens/ERC20/Web3+ERC20.swift, Sources/web3swift/Tokens/ERC721/Web3+ERC721.swift, Sources/web3swift/Tokens/ERC721x/Web3+ERC721x.swift, Sources/web3swift/Tokens/ERC777/Web3+ERC777.swift, Sources/web3swift/Tokens/ERC888/Web3+ERC888.swift, Sources/web3swift/Tokens/ST20/Web3+ST20.swift, Sources/web3swift/Tokens/ST20/Web3+SecurityToken.swift, Sources/web3swift/Utils/ENS/ENSBaseRegistrar.swift, Sources/web3swift/Utils/ENS/ENSRegistry.swift, Sources/web3swift/Utils/ENS/ENSResolver.swift, Sources/web3swift/Utils/ENS/ENSReverseRegistrar.swift, Sources/web3swift/Utils/ENS/ETHRegistrarController.swift, Tests/web3swiftTests/localTests/AdvancedABIv2Tests.swift, Tests/web3swiftTests/localTests/ERC20Tests.swift, Tests/web3swiftTests/localTests/PersonalSignatureTests.swift, Tests/web3swiftTests/localTests/UncategorizedTests.swift, Tests/web3swiftTests/localTests/UserCases.swift
Fixes #727
Local and remote tests runs correctly locally
=> Renamed callContractMethod to call for ReadOperation

Sources/Web3Core/KeystoreManager/BIP44.swift, Sources/Web3Core/KeystoreManager/EtherscanTransactionChecker.swift, Tests/web3swiftTests/localTests/BIP44Tests.swift, Tests/web3swiftTests/remoteTests/EtherscanTransactionCheckerTests.swift
This PR is related to #719, I have a local commit with the last changes but I forgot to push it and the branch was merged. I noticed it today.
Apologies, could you take a look @yaroslavyaroslav @JeneaVranceanu?
=> Feature BIP44(2/2)

Tests/web3swiftTests/localTests/EIP1559BlockTests.swift
=> Let's spell tuple correctly

Sources/Web3Core/EthereumABI/ABIEncoding.swift, Tests/web3swiftTests/localTests/ABIEncoderTest.swift
The initial bug was caught by mistake by using older version of the web3swift library.
But nonetheless an encoding bug was fixed: passing negative value to `ABIEncoder.encodeSingleType` with a type `.uint` must return `nil`.
For example, web3js produces `Uncaught Error: value out-of-bounds` for such cases. We are returning `nil` for now.
-----------------
Attempts to encode a negative number with ParameterType `.uint(...)` resulted in a crash.
~The fix is located in `ABIEncoder.convertToBigUInt`.~
- I have included test data or screenshots that prove my fix …
=> fix: attempt to encode uint with a negative value results in a crash

Tests/web3swiftTests/localTests/UtilitiesTests.swift
Triggered by https://github.com/web3swift-team/web3swift/pull/747
Test cases for the derivation of an Ethereum address from a public key.
=> test: added test cases for `func publicToAddress`

Web3Core.podspec, web3swift.podspec
Fixes Web3Core.podspec
before publish new version to Cocoapods, change `Podfile` like this:
```
pod 'web3swift', :git => 'https://github.com/web3swift-team/web3swift.git', :commit => '{merge commit}'
pod 'Web3Core', :git => 'https://github.com/web3swift-team/web3swift.git', :commit => '{merge commit}'
```
=> Fix: Web3Core.podspec

Sources/Web3Core/EthereumABI/ABIElements.swift
…Element` type thus it prevents Cocoapods to build.
This one fixes Cocoapods support.
One of a method of an `ABI` types has been declared as global, that prevents Cocoapods to build. Now it's moved as `private static` into `ABI.Element`.
=> Fix Cocoapods support

Sources/Web3Core/Utility/Utilities.swift, Tests/web3swiftTests/localTests/NumberFormattingUtilTests.swift
Fixing all SwiftLint issues in `Utilities.swift` file.
=> fix: swiftlint issues in Utilities.swift

Sources/Web3Core/EthereumNetwork/RequestParameter/RequestParameter+Encodable.swift, Sources/Web3Core/EthereumNetwork/RequestParameter/RequestParameter+RawRepresentable.swift, Sources/Web3Core/EthereumNetwork/RequestParameter/RequestParameter.swift, Sources/Web3Core/KeystoreManager/BIP32HDNode.swift, Sources/Web3Core/KeystoreManager/BIP44.swift, Sources/Web3Core/Transaction/EventfilterParameters.swift, Sources/Web3Core/Utility/Utilities.swift, Sources/web3swift/HookedFunctions/Web3+BrowserFunctions.swift, Sources/web3swift/Web3/Web3+Personal.swift, Tests/web3swiftTests/localTests/PersonalSignatureTests.swift
- Fixed Swift documentation alignment + updated it a bit in `extension Web3.Personal`;
- Minor spacings update;
- Removed some redundant comments that do not hold any value.
=> chore: docs fix after swiftlint

.github/workflows/macOS-tests.yml, .swiftlint.yml
https://github.com/realm/SwiftLint#xcode recommends
> If you wish to fix violations as well, your script could run `swiftlint --fix && swiftlint` instead of just `swiftlint`. This will mean that all correctable violations are fixed while ensuring warnings show up in your project for remaining violations.
https://github.com/realm/SwiftLint#auto-correct
> Standard linting is disabled while correcting because of the high likelihood of violations (or their offsets) being incorrect after modifying a file while applying corrections.
- I have updated my …
=> SwiftLint recommends a double run when fixing

Sources/web3swift/Utils/EIP/EIP4361.swift, Tests/web3swiftTests/localTests/EIP4361Test.swift
Previous regular expressions were not following all requirements of EIP4361.
The new regular expressions are generated out of ABNF rules which cover absolutely all **requirements**.
=> fix: EIP4361/SIWE - new regular expressions to cover all requirements

Sources/web3swift/Utils/ENS/ENS.swift, Sources/web3swift/Utils/ENS/ENSRegistry.swift, Sources/web3swift/Utils/ENS/ENSResolver.swift
Closes https://github.com/web3swift-team/web3swift/issues/787
Based on https://github.com/web3swift-team/web3swift/issues/731
Having doubts about creating doc
=> API update: input argument renaming and potentially expansion of allowed input

Sources/Web3Core/Contract/ContractProtocol.swift, Sources/Web3Core/EthereumABI/ABIDecoding.swift, Sources/Web3Core/EthereumABI/ABIElements.swift, Tests/web3swiftTests/localTests/ABIDecoderSliceTests.swift
Fixed issue https://github.com/web3swift-team/web3swift/issues/801
=> - ABIDecoding getting data slice in followTheData changed to using start data index

Sources/Web3Core/KeystoreManager/BIP32Keystore.swift, Tests/web3swiftTests/localTests/BIP32KeystoreTests.swift
- Generation amount of addresses added
- Generation wallet with index > 9 FIXED
- Test generation addresses added
I had added method for faster generation addresses by derivation path index in seed, and found bug with generation.
There was bug with generation wallets from seed when index has more than 1 symbol, for example:
address of wallet  "m/44'/60'/0'/1" same with wallet "m/44'/60'/0'/10" or "m/44'/60'/0'/121"
=> Addresses generator (#1)

Sources/web3swift/Web3/Web3+Signing.swift
For signing, add bool value using  hash or not .
There is the same bool argument for Web3j for Java.
This PR will help collaborate with Java developers.
=> feat: sign without hash

Sources/Web3Core/Contract/ContractProtocol.swift, Sources/Web3Core/EthereumABI/ABIElements.swift, Sources/Web3Core/Transaction/EventfilterParameters.swift, Sources/web3swift/EthereumAPICalls/Ethereum/IEth+Defaults.swift, Sources/web3swift/EthereumAPICalls/Ethereum/IEth.swift, Tests/web3swiftTests/localTests/EventTests.swift, Tests/web3swiftTests/remoteTests/EventFilterTests.swift
implement eth.getLogs to query events from evm, 
**Consult**:
https://github.com/ethers-io/ethers.js/blob/32915634bef5b81c6d9998f4e9ad812ffe721954/src.ts/abi/interface.ts#L1007
fix: `EventFilterParameters.encode()`, `Topic` can not encode as a single string
=> feat: implement eth_getLogs

Sources/Web3Core/KeystoreManager/BIP39.swift, Tests/web3swiftTests/localTests/BIP39Tests.swift
One of the users raised an issue where using a language any but English produces only English BIP39 mnemonics. This PR addresses the issue and adds a test to make sure each language uses the correct words.
Original report: https://discord.com/channels/852230666292559882/855075850771496971/1223929794383839293
None.
=> fix: BIP39 use given language to generate mnemonics;

Tests/web3swiftTests/remoteTests/EIP1559Tests.swift
Just noticed redundant `gasLimit` parameter in a few test cases. Decided to remove to avoid confusing other people.
=> chore: minor test update

.codespellrc
Current CI fails with codespell checks in secp256k1 directory.
=> chore: exclude secp256k1 from codespell

Sources/secp256k1/scalar_4x64_impl.h
Addresses an issue where builds initiated from Xcode 16 produced errors because of a missing import.
Fixes # 1 (a header import)
=> Imported <sys/types.h>

CONTRIBUTION.md
Update of the CONTRIBUTION.md.
=> chore: CONTRIBUTION.md update
