web3swift-team/web3swift

LICENSE

No more affiliation with Bankex

License got reverted somewhere after PRs

---

Documentation/Usage.md
README.md

Changes due to 2.0 version and some changes in ready/planned features

Documentation

---

web3swift/Transaction/Classes/EthereumTransaction.swift
web3swift/Web3/Classes/Web3+ReadingTransaction.swift
web3swift/Web3/Classes/Web3+Utils.swift
web3swiftTests/web3swift_promises_Tests.swift

This fixies #118 an 'estimate gas' bug (wrong gas estimations due to not passing gas price parameter)
Supplied gasPrice parameter to estimateGas func call.

fixed estimate gas problem

---

web3swift.podspec
web3swift.xcodeproj/project.pbxproj
web3swift/HookedFunctions/Classes/Web3+BrowserFunctions.swift

Hotfix: fixed browser functions and project

2.1.3 fix No2

---

CHANGELOG.md
web3swift.podspec
web3swift/Utils/ENS/ENS.swift
web3swift/Utils/ENS/ENSRegistry.swift
web3swift/Utils/ENS/ENSResolver.swift
web3swift/Utils/ENS/ENSReverseRegistrar.swift
web3swift/Utils/ENS/ETHRegistrarController.swift

Made most of ENS namespace classes props and methods public

Quickfix ens

---

Sources/web3swift/Convenience/SECP256k1.swift
Sources/web3swift/EthereumABI/ABIDecoding.swift
Sources/web3swift/HookedFunctions/Web3+BrowserFunctions.swift
Sources/web3swift/Transaction/EthereumTransaction.swift
Sources/web3swift/Transaction/TransactionSigner.swift
Sources/web3swift/Web3/Web3+Utils.swift
Tests/web3swiftTests/web3swift_keystores_Tests.swift

V handle fix

---

README.md

Hey, I will handle basic support of this library and will check, that it works with modern configurations. I moved all the details in pinned issue #231 and left there a brief notice.

improtant notice update

---

Sources/web3swift/Utils/ENS/ENSRegistry.swift

chore: update ENS Registry migration 

---

README.md

Added web3-react-native to libraries that use web3swift

---

Sources/web3swift/EthereumABI/ABIParsing.swift

key payable is nil and not defined for any functions

fix crash abi parsing

---

Sources/web3swift/Convenience/Data+Extension.swift
Sources/web3swift/Convenience/SECP256k1.swift
Sources/web3swift/KeystoreManager/BIP32HDNode.swift
Sources/web3swift/KeystoreManager/BIP32Keystore.swift
Sources/web3swift/KeystoreManager/BIP39.swift
Sources/web3swift/KeystoreManager/EthereumKeystoreV3.swift

Building on Valter4578's PR #443 this fixes the remaining 4 warnings.

Fix all warnings

---

Package.resolved
Package.swift

Freezing CryptoSwift dependency to last working version (1.4.3)

---

Sources/Core/Structure/Event+Protocol.swift
Sources/web3swift/Web3/Web3.swift

Add Goerli to Networks list
Add Infura Provider for Goerli
Update docs

Add goerli

---

Sources/Core/EthereumABI/ABIDecoding.swift

Dynamic array fix.

---

.github/workflows/macOS-12.yml

- Xcode 14.1
- Swift toolchain 5.7

Update actions Xcode version and Swift toolchain to latest

---

Sources/Core/Oracle/GasOracle.swift

Based on a discussion from Discord: https://discord.com/channels/852230666292559882/855075850771496971/1048956917197836368

fix: set public access modifier to FeeHistory struct members

---

.github/workflows/macOS-tests.yml

Just bringing develop-4.0 up to date. Next time will do it when there're more changes between develop-4.0 and develop.

Chore/develop v4.0 up to date

---

.github/workflows/macOS-tests.yml

https://github.com/actions/checkout/releases

Upgrade GitHub Action checkout

---

Sources/web3swift/Utils/EIP/EIP712.swift

Let's spell parameters correctly

---

Sources/Web3Core/KeystoreManager/IBAN.swift

Let's spell beginning correctly

---

.github/workflows/macOS-tests.yml
Tests/web3swiftTests/localTests/EIP1559BlockTests.swift

Use https://github.com/codespell-project/actions-codespell to discover typos like #743, #745, #746, #747, #748

GitHub Actions: Add codespell to find typos

---

Sources/web3swift/Utils/EIP/EIP681.swift

Let’s spell parameters correctly

---

Sources/web3swift/Utils/ENS/ENSBaseRegistrar.swift

Typo fix. Triggered by codespell.

chore: fixed typo in a comment in ENSBaseRegistrar.swift

---

Tests/web3swiftTests/remoteTests/TransactionPollingTaskRemoteTest.swift

Add transaction awaiting task remote test
